package org.jackJew.interview;

public class ObjectHashCode {

	public static void main(String[] args) {
		Object obj1 = new Object();
		System.out.println(obj1.hashCode());
		
		Object obj2 = new Object();
		System.out.println(obj2.hashCode());
		
		System.out.println("------------------------");
		
		System.out.println(System.identityHashCode(obj1));
		System.out.println(System.identityHashCode(obj2));
		
		// now we see that Object.hashCode() or classes that not overriding hashCode() will use 
		// identity hashcode generated by System based on memory address.
	}

}
